{% set name = "dash-leaflet" %}
{% set version = "1.0.13" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_leaflet-{{ version }}.tar.gz
  sha256: ef5ae3cae598eca40cfbd9a0774dde85c8b80a5b1d7e9b2988328bca5ae3bb37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash
    - geobuf
    - python >=3.6

test:
  imports:
    - dash_leaflet
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/thedirtyfew/dash-leaflet
  summary: Leaflet component for Dash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mitchellwood
