{% set name = "dash-leaflet" %}
{% set version = "0.1.22" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_leaflet-{{ version }}.tar.gz
  sha256: 5b652df86585c09a7623730799cc29a66871c11691a1353749a9f881e0a85fc0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash
    - geobuf
    - python >=3.6

test:
  imports:
    - dash_leaflet
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/thedirtyfew/dash-leaflet
  summary: Leaflet component for Dash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mitchellwood
