{% set name = "dash-leaflet" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_leaflet-{{ version }}.tar.gz
  sha256: 46cbb825a7da7917a1d4b4c174f9b3f6d5615a87ec4179cbd1a84749f78452a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dash
    - geobuf
    - python >=3.6

test:
  imports:
    - dash_leaflet
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/thedirtyfew/dash-leaflet
  summary: Leaflet component for Dash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mitchellwood
